source: 'index.html.template'
target: 'index.html'
keys:
  photos:
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/2023-10-28-moon-eclipse-big.jpg'
        small_img_path:    'photos/2023-10-28-moon-eclipse-small.jpg'
        img_alt_name:      'Moon eclipse 2023-10-28'
        object_catalogue:  'Moon'
        object_number:     'eclipse 2023'
        object_name:       ''
        telescope:         'FRA300'
        mount:             'EQ6R'
        camera:            'ASI533MC'
        filters:           'full spectrum RGB converted to gray'
        expositions:       'L: 18 frames 2-1000ms, gain 0-450'
        date:              '28.10.2023 17:30-21:30 UTC'
        sky:               'Bortle 9'
        extra_description: "catched through thick clouds in bad conditions, stacked 13k frames chosen manually from 131k frames"
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'https://www.youtube.com/watch?v=LaoYKK6UJZ8'
        small_img_path:    'photos/2023-10-28-moon-eclipse-small.jpg'
        img_alt_name:      'Moon eclipse 2023-10-28'
        object_catalogue:  'Moon'
        object_number:     'eclipse 2023'
        object_name:       ''
        telescope:         'FRA300'
        mount:             'EQ6R'
        camera:            'ASI533MC'
        filters:           'full spectrum RGB converted to gray'
        expositions:       'L: 18 frames 2-1000ms, gain 0-450'
        date:              '28.10.2023 17:30-21:30 UTC'
        sky:               'Bortle 9'
        extra_description: "catched through thick clouds in bad conditions, stacked 13k frames chosen manually from 131k frames"
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'sun'
        full_path:         'https://www.youtube.com/watch?v=RmX_DRl4MaY'
        small_img_path:    'photos/sun-airplane1-small.jpg'
        img_alt_name:      'sun airplane 1'
        object_catalogue:  'Sun'
        object_number:     'airplane vid'
        object_name:       ''
        telescope:         'ED 72'
        mount:             'Trident P75'
        camera:            'ASI432MM'
        filters:           'Quark Chromo'
        expositions:       'L: 2000 x 3ms'
        date:              '20.09.2023 08:24 UTC'
        sky:               'Bortle 9'
        extra_description: "it's EI-ENX RYR6WF FR353 B737-8AS"
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'sun'
        full_path:         'photos/sun-airplane1-raw.jpg'
        small_img_path:    'photos/sun-airplane1-small.jpg'
        img_alt_name:      'sun airplane 1'
        object_catalogue:  'Sun'
        object_number:     'airplane raw'
        object_name:       'single raw frame'
        telescope:         'ED 72'
        mount:             'Trident P75'
        camera:            'ASI432MM'
        filters:           'Quark Chromo'
        expositions:       'L: 2000 x 3ms'
        date:              '20.09.2023 08:24 UTC'
        sky:               'Bortle 9'
        extra_description: "it's EI-ENX RYR6WF FR353 B737-8AS"
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/moon-2023-05-03.jpg'
        small_img_path:    'photos/moon-2023-05-03-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '03.05.2023'
        object_name:       ''
        telescope:         'N 200/1000'
        mount:             'EQ6R'
        camera:            'ASI533MM'
        filters:           'Astronomik IR642'
        expositions:       'L: 5000 x 5ms'
        date:              '03.05.2023'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/2023-02-06-1.jpg'
        small_img_path:    'photos/2023-02-06-1-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '06.02.2023'
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 5000 x 5ms'
        date:              '06.02.2023'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/2023-02-06-2.jpg'
        small_img_path:    'photos/2023-02-06-2-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '06.02.2023'
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 5000 x 5ms'
        date:              '06.02.2023'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/2023-02-06-3.jpg'
        small_img_path:    'photos/2023-02-06-3-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '06.02.2023'
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 5000 x 5ms'
        date:              '06.02.2023'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/2023-02-06-4.jpg'
        small_img_path:    'photos/2023-02-06-4-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '06.02.2023'
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 5000 x 5ms'
        date:              '06.02.2023'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'moon'
        full_path:         'photos/moon-2022-12-30.jpg'
        small_img_path:    'photos/moon-2022-12-30-small.jpg'
        img_alt_name:      'moon'
        object_catalogue:  'Moon'
        object_number:     '30.12.2022'
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 3000 x 5ms'
        date:              '30.12.2022'
        sky:               'bortle 9'
        extra_description: 'AS3, pixinsight, sharpened using blurXterminator'
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'comet'
        full_path:         'photos/67p.jpg'
        small_img_path:    'photos/67p-small.jpg'
        img_alt_name:      'comet 67p'
        object_catalogue:  'Comet'
        object_number:     '67p'
        object_name:       'Churyumov-Gerasimenko'
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 1 x 60s'
        date:              '30.10.2021 21:34 UTC'
        sky:               'bortle 9'
        extra_description: ''
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'comet'
        full_path:         'https://www.youtube.com/watch?v=WcR4X8jhQLo'
        small_img_path:    'photos/67p-small.jpg'
        img_alt_name:      'comet 67p'
        object_catalogue:  'Comet'
        object_number:     '67p &nbsp vid'
        object_name:       'Churyumov-Gerasimenko'
        telescope:         'CC 200/2450'
        mount:             'EQ6R'
        camera:            'ASI183MM'
        filters:           'ZWO G'
        expositions:       'L: 117 x 60s'
        date:              '30.10.2021 21:34 UTC - 23:30 UTC'
        sky:               'Bortle 9'
        extra_description: ''
    -
      file: 'gallery.html.template'
      duplicate:
        object_type:       'all_objects'
      parameters:
        object_type:       'planetoid_dwarf'
        full_path:         'photos/pluto_2021.jpg'
        small_img_path:    'photos/pluto_2021-small.jpg'
        img_alt_name:      'pluto 2021'
        object_catalogue:  'Pluto'
        object_number:     ''
        object_name:       ''
        telescope:         'CC 200/2450'
        mount:             'EQ5 DIY GOTO'
        camera:            'ASI462MC'
        filters:           'full spectrum'
        expositions:       'OSC: 1 x 20s'
        date:              '29.07.2021 20:50 UTC'
        sky:               'Bortle 9'
        extra_description: ''

  projects:
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/szkolenia.jpg'
        html_content: |
          <p><b><h4>My trainings, handbooks and tutorials</h4></b></p>
          <p><ul style="list-style: inside;">
          <li>Puppet 4 PL</li>
          <li>Linux basics PL</li>
          <li>Docker PL</li>
          </ul></p>
          <p><a href="https://github.com/lkosz/szkolenia">https://github.com/lkosz/szkolenia</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/gears.png'
        html_content: |
          <p><b><h4>Drive for EQ3-2</h4></b></p>
          2-axis drive for EQ3-2 - schema + Arduino code + 3D models of gears and cases for both RA and DEC axis
          <p><a href="https://github.com/lkosz/eq3-2_drive">https://github.com/lkosz/eq3-2_drive</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/elektrofiszki.png'
        html_content: |
          <p><b><h4>Flash cards</h4></b></p>
          This program is like flash cards but in electronic way. Choose between several languages, add any word/words/phrases/meanings you want. Program will ask for it and read back using voice from google translate to remember pronunciation. If you write correct answer (one of correct answers), word level is incremented which means program will ask again for it in longer period. Level 1 is after 5min, level 20 is after 72 days. If you answer wrong - level is decremented.
          <p><a href="https://github.com/lkosz/elektrofiszki">https://github.com/lkosz/elektrofiszki</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/4mag2021.jpg'
        html_content: |
          <p><b><h4>Determine star magnitude which can be seen during midday 2021</h4></b></p>
          it is said that 4 mag stars and brighter can be seen during the day - try to check it
          <p><a href="https://github.com/lkosz/astronomy/tree/main/daylight_star_magnitude">https://github.com/lkosz/astronomy/tree/main/daylight_star_magnitude</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/eq5_goto.jpg'
        html_content: |
          <p><b><h4>DIY GOTO for EQ5 + DIY guiding</h4></b></p>
          GOTO computer for equatorial mount EQ5. Goal: goto with accuracy better than 10 arcsec, DIY guiding. All cost much less than EQ6-R. Unfortunately quality of EQ5 is poor so guiding have accuracy greater than 1"
          <p><a href="https://github.com/lkosz/eq5_goto">https://github.com/lkosz/eq5_goto</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/astro_gui.png'
        html_content: |
          <p><b><h4>App for DIY GOTO, getting frames from cameras and platesolve</h4></b></p>
          There are two apps - app1 is for my EQ5 GOTO, app2 is to run with EQ6-R. Both are for photo acquisition, platesolving, automatization
          <p><a href="https://github.com/lkosz/astro_camera_gui">https://github.com/lkosz/astro_camera_gui</a></p>
    -
      file: 'project.html.template'
      parameters:
        image: 'projects/filterwheel.jpg'
        html_content: |
          <p><b><h4>Filterwheel for 18 1.25" astronomy filters</h4></b></p>
          Controlled via my gui apps (via REST API)
          <p><a href="https://github.com/lkosz/astro_filterwheel">https://github.com/lkosz/astro_filterwheel</a></p>

  aboutme:
    -
      file: 'project.html.template'
      parameters:
        image: 'img/001.jpg'
        html_content: |
          <p>My name is Łukasz Koszyk and I'm a mathematician interrested in mathematical analysis, Linux admin. DevOPS, SysOPS, Linux, Puppet, Bash, Python, CentOS/Rocky Linux, Kubernetes, network debugging, IaaS, IaaC, security. Can't live without Elasticsearch, Grafana and Kibana.</p>
          <p>My interests:</p>
          <ul class="about-us-list">
              <li class="points"><b>Astronomy:</b> space imaging in bands from UV to SWIR under Bortle 9, Planets and weak Solar System objects, small and planetary nebulas, globular clusters. Radioastronomy on wish list</li>
              <li class="points"><b>Data analysis:</b> air pollution and weather extremes, climate change</li>
              <li class="points"><b>Electronics:</b> self-made PCBs, devices based on microcontrollers, Raspberry, and plain TTL/CMOS chips</li>
              <li class="points"><b>3D FDM:</b> printing and modeling using OpensCAD</li>
              <li class="points"><b>Aviation:</b> love to fly A319 in bad weather conditions using VOR/DME or NDB. Favourite airports: LOWI, LOWK, VQPR, LGSM, LSZS</li>
              <li class="points">Play on kalimba</li>
          </ul>

